export default {
  ui: {
    appTitle: "Islamic Wisdom Flashcards",
    appSubtitle: "Tap a topic/category → tap the card to flip → no repeats until the deck is complete.",
    frontHint: "Tap to flip • Pick a button to draw the next card",
    footerTip: "Tip: Progress is saved per category and language (no repeats until you finish the deck).",
    selectPrompt: "Select a category",
    noContent: "No content yet for this deck.",
    methodTitle: "Practical method",
  },

  labels: {
    topics: {
      "Prophet Muhammad ﷺ Wisdom": "Prophet Muhammad ﷺ Wisdom",
      "Quran": "Quran",
      "Dhikr & Dua": "Dhikr & Dua",
      "Salah": "Salah",
      "Ramadan": "Ramadan",
      "Poison of the Heart": "Poison of the Heart",
      "Tricks of Shaytan": "Tricks of Shaytan",
    },
    categories: {
      "Anger":"Anger",
      "Anxiety":"Anxiety",
      "Envy/Hasad":"Envy/Hasad",
      "Jealousy":"Jealousy",
      "Tongue":"Tongue",
      "Pride/Kibr":"Pride/Kibr",
      "Greed":"Greed",
      "Fear":"Fear",
      "Sadness & Grief":"Sadness & Grief",
      "Loneliness":"Loneliness",
      "Sabr":"Sabr",
      "Tawakkul":"Tawakkul",
      "Aqeedah":"Aqeedah",
      "Adab":"Adab",
      "Dawah":"Dawah",
      "Akhira":"Akhira",
      "Family & Spouse":"Family & Spouse",
      "Children":"Children",
      "Women in Islam":"Women in Islam",
      "Sahaba & Parables":"Sahaba & Parables",
    }
  },

  decks: {
    topics: {
      // Keep topic decks short here; expand freely later
      "Prophet Muhammad ﷺ Wisdom": [
        { text: "Actions are only by intentions.", source: "Sahih al-Bukhari & Sahih Muslim (Hadith of Intention)" },
        { text: "The strong one is not the one who overcomes people by strength, but the one who controls himself when angry.", source: "Sahih al-Bukhari 6114/6116 (wording varies)" },
        { text: "None of you truly believes until he loves for his brother what he loves for himself.", source: "Sahih al-Bukhari & Sahih Muslim" },
        { text: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.", source: "Sahih al-Bukhari & Sahih Muslim" },
        { text: "Allah is gentle and loves gentleness in all matters.", source: "Sahih Muslim (Rifq / gentleness)" },
      ],
      "Quran": [
        { text: "Indeed, Allah is with the patient.", source: "Quran 2:153" },
        { text: "Surely, in the remembrance of Allah do hearts find rest.", source: "Quran 13:28" },
        { text: "So remember Me; I will remember you.", source: "Quran 2:152" },
        { text: "Allah does not burden a soul beyond what it can bear.", source: "Quran 2:286" },
        { text: "With hardship comes ease.", source: "Quran 94:5–6" },
      ],
      "Dhikr & Dua": [
        { text: "The likeness of the one who remembers his Lord and the one who does not is like the living and the dead.", source: "Sahih al-Bukhari" },
        { text: "Supplication is worship.", source: "Jami` at-Tirmidhi" },
        { text: "Say: Hasbunallahu wa ni'mal wakeel (Allah is sufficient for us and the best disposer of affairs).", source: "Quran 3:173" },
        { text: "O Turner of hearts, keep my heart firm upon Your religion.", source: "Jami` at-Tirmidhi (du'a)" },
        { text: "Astaghfirullah (seeking forgiveness) brings relief and provision.", source: "Meaning supported by hadith narrations on istighfar" },
      ],
      "Salah": [
        { text: "Establish prayer for My remembrance.", source: "Quran 20:14" },
        { text: "The closest a servant is to his Lord is while prostrating.", source: "Sahih Muslim" },
        { text: "Prayer prevents immorality and wrongdoing.", source: "Quran 29:45" },
        { text: "Seek help through patience and prayer.", source: "Quran 2:45" },
        { text: "Guard strictly the prayers.", source: "Quran 2:238" },
      ],
      "Ramadan": [
        { text: "Fasting is prescribed for you so that you may attain taqwa.", source: "Quran 2:183" },
        { text: "Whoever fasts Ramadan out of faith and seeking reward will have his past sins forgiven.", source: "Sahih al-Bukhari & Sahih Muslim" },
        { text: "The smell of the fasting person’s mouth is better to Allah than musk.", source: "Sahih al-Bukhari & Sahih Muslim" },
        { text: "Laylat al-Qadr is better than a thousand months.", source: "Quran 97:3" },
        { text: "In Ramadan, the gates of Paradise are opened.", source: "Sahih al-Bukhari & Sahih Muslim" },
      ],
      "Poison of the Heart": [
        { text: "On the Day when neither wealth nor children will benefit—only a sound heart.", source: "Quran 26:88–89" },
        { text: "Beware of envy, for it consumes good deeds like fire consumes wood.", source: "Sunan Abi Dawud (meaning widely cited)" },
        { text: "In the body there is a piece of flesh; if it is sound, the whole body is sound.", source: "Sahih al-Bukhari & Sahih Muslim" },
        { text: "He has succeeded who purifies it (the soul).", source: "Quran 91:9" },
        { text: "Do not let hatred cause you to be unjust.", source: "Quran 5:8" },
      ],
      "Tricks of Shaytan": [
        { text: "Indeed, Shaytan is an enemy to you, so take him as an enemy.", source: "Quran 35:6" },
        { text: "He only invites his party to be among the companions of the Blaze.", source: "Quran 35:6 (continuation)" },
        { text: "Shaytan threatens you with poverty and orders immorality.", source: "Quran 2:268" },
        { text: "Seek refuge in Allah from Shaytan, the accursed.", source: "Quran 16:98" },
        { text: "Verily, the plot of Shaytan is weak.", source: "Quran 4:76" },
      ],
    },

    categories: {
      // For “starter deck” size: some categories are 20, others are 10.
      // Expand each to 365 by appending items.

      "Anger": [
        { text: "Those who restrain anger and pardon people—Allah loves the doers of good.", source: "Quran 3:134", method: "Do wudu, sit if standing, lie down if sitting, and say: A‘udhu billahi min ash-shaytan ir-rajim." },
        { text: "Do not get angry.", source: "Sahih al-Bukhari", method: "Pause before responding; breathe slowly; delay the conversation until calm." },
        { text: "The strong one is the one who controls himself when angry.", source: "Sahih al-Bukhari (anger hadith)", method: "Name the emotion, lower the voice, and leave the place for 2 minutes." },
        { text: "And lower your voice; indeed, the harshest of voices is the braying of donkeys.", source: "Quran 31:19", method: "Lower volume intentionally; speak in short, calm sentences." },
        { text: "Repel evil with that which is better.", source: "Quran 41:34", method: "Answer harshness with calm; make du‘a for the person." },
        { text: "When one of you is angry while standing, let him sit.", source: "Abu Dawud (meaning cited)", method: "Change posture; drink water; step away from triggers." },
        { text: "Pardon and overlook—would you not love that Allah should forgive you?", source: "Quran 24:22", method: "Remind yourself: forgiveness is a door to Allah’s forgiveness." },
        { text: "Say good or remain silent.", source: "Bukhari & Muslim", method: "If you can’t say it gently, say nothing until you can." },
        { text: "And the servants of the Most Merciful… when addressed by the ignorant, they say: Peace.", source: "Quran 25:63", method: "Exit arguments; respond with 'peace' and disengage." },
        { text: "Patience is at the first strike of calamity.", source: "Sahih al-Bukhari & Sahih Muslim", method: "Train the 'first reaction': dhikr + silence + posture change." },
        // (add 10 more to reach 20 later)
      ],

      "Anxiety": [
        { text: "Surely, in the remembrance of Allah do hearts find rest.", source: "Quran 13:28", method: "10 minutes: slow breathing + 'La ilaha illa Allah' + reflect on Allah’s Names." },
        { text: "Allah does not burden a soul beyond what it can bear.", source: "Quran 2:286", method: "Rewrite the worry: 'Allah gave me capacity' → take one next step only." },
        { text: "With hardship comes ease.", source: "Quran 94:5–6", method: "Pair every worry with an action: what is one controllable step today?" },
        { text: "And whoever relies upon Allah—He is sufficient for him.", source: "Quran 65:3", method: "Do the means, then release the outcome: 'Hasbi Allah' repeatedly." },
        { text: "Say: Nothing will happen to us except what Allah has decreed for us.", source: "Quran 9:51", method: "Reduce doom loops: accept decree, focus on obedience now." },
        { text: "O you who believe, seek help through patience and prayer.", source: "Quran 2:153", method: "Pray 2 rak‘ah; make du‘a with presence; then do one task." },
        { text: "When you ask, ask Allah; when you seek help, seek Allah.", source: "Tirmidhi (Ibn Abbas advice)", method: "Turn the worry into du‘a; name your fear; ask for steadfastness." },
        { text: "Verily, Allah is with the patient.", source: "Quran 2:153", method: "Practice 'Sabr moments': delay reacting by 30 seconds with dhikr." },
        { text: "My servants who have transgressed… do not despair of Allah’s mercy.", source: "Quran 39:53", method: "If anxiety is guilt-driven: make tawbah plan + hopeful du‘a." },
        { text: "Remember your Lord within yourself… and do not be among the heedless.", source: "Quran 7:205", method: "Micro-dhikr all day: after each notification, say one tasbih." },
      ],

      "Envy/Hasad": [
        { text: "Do not envy one another.", source: "Sahih Muslim (meaning)", method: "Make du‘a for the person’s barakah; train the heart to love الخير للناس." },
        { text: "Envy consumes good deeds like fire consumes wood.", source: "Abu Dawud (meaning widely cited)", method: "When envy appears: say 'Allahumma barik lah' (O Allah bless them) immediately." },
        { text: "And from the evil of an envier when he envies.", source: "Quran 113:5", method: "Recite Al-Falaq & An-Nas morning/evening; seek protection consistently." },
        { text: "We have apportioned among them their livelihood in the life of this world.", source: "Quran 43:32", method: "Reframe: provision is Allah’s distribution; pursue halal effort without resentment." },
        { text: "Look to those below you… it is more likely you will not belittle Allah’s favors.", source: "Sahih Muslim", method: "Gratitude audit: write 5 favors daily." },
        { text: "Whoever believes… love for your brother what you love for yourself.", source: "Bukhari & Muslim", method: "Flip the envy: wish them good and ask Allah for similar (without removal)." },
        { text: "Do not wish for what Allah has favored some of you over others.", source: "Quran 4:32", method: "Ask Allah from His bounty; set personal goals rather than comparisons." },
        { text: "Indeed, Allah loves those who repent and purify themselves.", source: "Quran 2:222", method: "Treat envy as a spiritual impurity: tawbah + dhikr + good deed." },
        { text: "Allah is the Bestower; He gives without account.", source: "Meaning based on Quranic descriptions", method: "Repeat: 'Ya Razzaq' and make specific du‘a for halal increase." },
        { text: "He has succeeded who purifies the soul.", source: "Quran 91:9", method: "Do hidden charity; it breaks ego and envy." },
      ],

      "Jealousy": [
        { text: "Avoid suspicion… and do not spy or backbite one another.", source: "Quran 49:12", method: "When jealousy triggers suspicion: stop, verify gently, assume good first." },
        { text: "And live with them in kindness.", source: "Quran 4:19", method: "Replace control with care: communicate needs calmly, set boundaries with ihsan." },
        { text: "The believers are but brothers, so make settlement between your brothers.", source: "Quran 49:10", method: "If jealousy is social: reconcile, don’t compete; make du‘a for unity." },
        { text: "Allah knows what is within your hearts.", source: "Quran 3:154 (theme)", method: "Do heart-muhasabah: name insecurity; seek healing through dhikr & counseling if needed." },
        { text: "Love for others what you love for yourself.", source: "Bukhari & Muslim", method: "Practice gratitude + du‘a for others; jealousy weakens with sincere الخير." },
        { text: "If you are grateful, I will surely increase you.", source: "Quran 14:7", method: "Shift focus: gratitude journaling daily; you’ll feel less threatened." },
        { text: "Do not let hatred cause you to be unjust.", source: "Quran 5:8", method: "Commit to fairness even when feelings flare; choose adl over emotion." },
        { text: "Indeed, Shaytan sows discord between them.", source: "Quran 17:53 (theme)", method: "Recognize the whisper: discord is a trap—seek refuge and repair." },
        { text: "Pardon and overlook.", source: "Quran 24:22 (theme)", method: "Forgive small slights; don’t build narratives." },
        { text: "And speak to people good words.", source: "Quran 2:83 (theme)", method: "Choose gentle speech; it neutralizes jealous escalation." },
      ],

      "Tongue": [
        { text: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.", source: "Bukhari & Muslim", method: "Use the 3-filter rule: true, kind, necessary." },
        { text: "Do not backbite one another.", source: "Quran 49:12", method: "If you slip: stop immediately, seek forgiveness, and make du‘a for the person." },
        { text: "Not a word does he utter except that with him is an observer prepared.", source: "Quran 50:18", method: "Before speaking: imagine it written permanently; choose carefully." },
        { text: "And tell My servants to say that which is best.", source: "Quran 17:53", method: "Replace harshness with the best possible phrasing." },
        { text: "Woe to every scorner and mocker.", source: "Quran 104:1", method: "Stop sarcasm that wounds; train respect." },
        { text: "Speak a word of appropriate justice.", source: "Quran 33:70", method: "Aim for precise, fair speech—no exaggeration." },
        { text: "A person may utter a word… that plunges him into the Fire.", source: "Bukhari & Muslim (meaning)", method: "Slow down: speak less, reflect more." },
        { text: "And do not pursue that of which you have no knowledge.", source: "Quran 17:36", method: "No forwarding rumors. Verify first." },
        { text: "Invite to the way of your Lord with wisdom and good instruction.", source: "Quran 16:125", method: "Soft start + empathy + evidence." },
        { text: "The best of you are those who are best in manners.", source: "Hadith meaning", method: "Make adab your default tone." },
      ],

      // The rest: seeded with 10 each (expand later)

      "Pride/Kibr": [
        { text: "Allah does not like every self-deluded boaster.", source: "Quran 31:18 (theme)" , method:"Practice hidden good deeds; remember your origin and your end."},
        { text: "Whoever has an atom’s weight of pride in his heart will not enter Paradise.", source: "Sahih Muslim", method:"Define pride: rejecting truth & looking down on people; repent immediately."},
        { text: "Do not turn your cheek in contempt toward people.", source: "Quran 31:18", method:"Train humility: greet first, apologize quickly, listen more."},
        { text: "And do not walk upon the earth exultantly.", source: "Quran 17:37", method:"Use humble body language; avoid showing off."},
        { text: "The most noble of you in Allah’s sight is the most righteous.", source: "Quran 49:13", method:"Compete only in taqwa, not status."},
        { text: "He has succeeded who purifies the soul.", source: "Quran 91:9", method:"Daily muhasabah: where did ego lead me today?"},
        { text: "And the servants of the Most Merciful walk humbly.", source: "Quran 25:63", method:"Choose calm, gentle presence."},
        { text: "O people, you are the needy of Allah.", source: "Quran 35:15", method:"Repeat: 'I need Allah for every breath'."},
        { text: "Do not claim yourselves to be pure.", source: "Quran 53:32", method:"Avoid self-praise; let deeds speak."},
        { text: "Whoever humbles himself for Allah, Allah raises him.", source: "Hadith meaning", method:"Seek humility intentionally; accept advice."},
      ],

      "Greed": [
        { text: "You will not attain righteousness until you spend from that which you love.", source: "Quran 3:92", method:"Schedule small weekly charity from your favorite things." },
        { text: "The worldly life is but enjoyment of delusion.", source: "Quran 3:185 (theme)", method:"Remember death daily; it shrinks greed." },
        { text: "Rivalry in worldly increase distracts you.", source: "Quran 102:1", method:"Limit comparison; set akhirah goals." },
        { text: "Wealth and children are a trial.", source: "Quran 64:15", method:"Ask: does this purchase bring me closer to Allah or just ego?" },
        { text: "Charity does not decrease wealth.", source: "Sahih Muslim", method:"Give consistently—even small." },
        { text: "Be in the world as though a stranger or traveler.", source: "Sahih al-Bukhari", method:"Adopt minimalism; keep your heart light." },
        { text: "Spend; it will be spent on you.", source: "Hadith meaning", method:"Automate sadaqah monthly." },
        { text: "The hand above is better than the hand below.", source: "Bukhari & Muslim", method:"Aim to be a giver, not a taker." },
        { text: "Do not withhold, or Allah will withhold from you.", source: "Hadith meaning", method:"Treat giving as protection, not loss." },
        { text: "And do good; Allah loves the doers of good.", source: "Quran 2:195 (theme)", method:"Channel desire into generosity." },
      ],

      "Fear": [
        { text: "So do not fear them; fear Me.", source: "Quran 3:175 (theme)", method:"Convert people-fear into Allah-fear: obey Allah first." },
        { text: "And whoever fears Allah—He will make for him a way out.", source: "Quran 65:2", method:"When afraid: seek halal exit, avoid haram shortcuts." },
        { text: "Indeed, the friends of Allah—no fear will there be concerning them.", source: "Quran 10:62", method:"Strengthen iman: consistent salah + dhikr." },
        { text: "Allah is sufficient for us and the best disposer of affairs.", source: "Quran 3:173", method:"Repeat during threats; take means calmly." },
        { text: "Verily, the plot of Shaytan is weak.", source: "Quran 4:76", method:"Name the whisper: 'This is intimidation'; seek refuge." },
        { text: "Do not despair of Allah’s mercy.", source: "Quran 39:53", method:"Hope is worship; keep returning." },
        { text: "Whoever relies upon Allah—He is sufficient for him.", source: "Quran 65:3", method:"Tawakkul plan: means + du‘a + release outcome." },
        { text: "Indeed, Allah is with those who are mindful of Him.", source: "Quran 16:128 (theme)", method:"Taqwa reduces fear of creation." },
        { text: "Say: Nothing will happen except what Allah has decreed.", source: "Quran 9:51", method:"Ground yourself in qadar." },
        { text: "Ask Allah for well-being.", source: "Hadith meaning", method:"Du‘a for ‘afiyah morning and evening." },
      ],

      "Sadness & Grief": [
        { text: "Do not despair of Allah’s mercy.", source: "Quran 39:53", method:"Name grief → du‘a → small daily worship anchor." },
        { text: "So truly with hardship comes ease.", source: "Quran 94:5–6", method:"List 1 ease you still have today." },
        { text: "Indeed, Allah is with the patient.", source: "Quran 2:153", method:"Sabr routine: salah on time + Qur’an daily even if short." },
        { text: "Indeed we belong to Allah, and to Him we return.", source: "Quran 2:156", method:"Say istirja’ and make du‘a for reward." },
        { text: "So be patient with gracious patience.", source: "Quran 70:5", method:"No complaining to people—complain to Allah in sujud." },
        { text: "And He found you lost and guided you.", source: "Quran 93 (theme)", method:"Read Surah Ad-Duha when low." },
        { text: "Your Lord has not forsaken you.", source: "Quran 93:3", method:"Repeat this ayah; fight abandonment thoughts." },
        { text: "The believer’s affair is all good.", source: "Sahih Muslim (meaning)", method:"Reframe pain as purification and elevation." },
        { text: "Allah is near to the broken-hearted.", source: "Meaning (not a hadith text)", method:"Turn to Allah with honesty; seek community support." },
        { text: "He has succeeded who purifies the soul.", source: "Quran 91:9", method:"Use grief to soften the heart, not harden it." },
      ],

      "Loneliness": [
        { text: "And He is with you wherever you are.", source: "Quran 57:4", method:"When lonely: dhikr + Qur’an + message one righteous friend." },
        { text: "Surely, in the remembrance of Allah do hearts find rest.", source: "Quran 13:28", method:"Create a daily 'with Allah' hour: Qur’an + du‘a." },
        { text: "The believers are but brothers.", source: "Quran 49:10", method:"Join the masjid/community; regular circles." },
        { text: "Keep yourself patient with those who call upon their Lord morning and evening.", source: "Quran 18:28", method:"Choose companionship of dhikr." },
        { text: "Whoever treads a path seeking knowledge, Allah eases his path to Paradise.", source: "Sahih Muslim", method:"Attend a class—build bonds through ilm." },
        { text: "Allah is the Protector of those who believe.", source: "Quran 2:257", method:"Repeat: 'Allah is my Wali' when isolated." },
        { text: "Do not walk on the earth exultantly.", source: "Quran 17:37 (theme)", method:"Replace isolation-pride with humility and outreach." },
        { text: "Speak good words to people.", source: "Quran 2:83 (theme)", method:"Initiate salam; it opens doors." },
        { text: "And cooperate in righteousness and piety.", source: "Quran 5:2", method:"Volunteer: service reduces loneliness." },
        { text: "The servant is closest to his Lord in sujud.", source: "Sahih Muslim", method:"Make long sujud; pour your heart out." },
      ],

      "Sabr": [
        { text: "Indeed, Allah is with the patient.", source: "Quran 2:153" },
        { text: "Give glad tidings to the patient.", source: "Quran 2:155–157" },
        { text: "So be patient with gracious patience.", source: "Quran 70:5" },
        { text: "Patience is light.", source: "Sahih Muslim (meaning)" },
        { text: "No fatigue nor illness afflicts a Muslim except Allah expiates sins thereby.", source: "Bukhari & Muslim (meaning)" },
        { text: "Seek help through patience and prayer.", source: "Quran 2:45" },
        { text: "And be patient, for your patience is only by Allah.", source: "Quran 16:127" },
        { text: "The reward of patience is without measure.", source: "Quran 39:10 (theme)" },
        { text: "Whoever remains patient, Allah will make him patient.", source: "Bukhari & Muslim (meaning)" },
        { text: "And the end is for the righteous.", source: "Quran 11:49 (theme)" },
      ],

      "Tawakkul": [
        { text: "And whoever relies upon Allah—He is sufficient for him.", source: "Quran 65:3" },
        { text: "If you relied upon Allah truly, He would provide for you like He provides for birds.", source: "Tirmidhi (meaning)" },
        { text: "So put your trust in Allah.", source: "Quran 3:159 (theme)" },
        { text: "Allah loves those who rely upon Him.", source: "Quran 3:159 (theme)" },
        { text: "Hasbunallahu wa ni‘mal wakeel.", source: "Quran 3:173" },
        { text: "Tie your camel and trust in Allah.", source: "Hadith meaning (tawakkul with means)" },
        { text: "And Allah is the best disposer of affairs.", source: "Quran 3:173 (theme)" },
        { text: "My success is only by Allah.", source: "Quran 11:88 (theme)" },
        { text: "Fear not. Indeed, I am with you.", source: "Quran 20:46 (theme)" },
        { text: "And He is the best of planners.", source: "Quran 8:30 (theme)" },
      ],

      "Aqeedah": [
        { text: "Say: He is Allah, One.", source: "Quran 112:1" },
        { text: "There is nothing like unto Him.", source: "Quran 42:11" },
        { text: "Allah—there is no deity except Him, the Ever-Living.", source: "Quran 2:255" },
        { text: "He neither begets nor is born.", source: "Quran 112:3" },
        { text: "To Allah belong the best Names, so call upon Him by them.", source: "Quran 7:180" },
        { text: "This day I have perfected for you your religion.", source: "Quran 5:3 (theme)" },
        { text: "Worship Allah and associate nothing with Him.", source: "Quran 4:36 (theme)" },
        { text: "So know that there is no deity except Allah.", source: "Quran 47:19" },
        { text: "We believe in Allah and what was revealed.", source: "Quran 2:136 (theme)" },
        { text: "Indeed, Allah is over all things competent.", source: "Quran 2:20 (theme)" },
      ],

      "Adab": [
        { text: "And speak to people good words.", source: "Quran 2:83 (theme)" },
        { text: "Walk humbly and when addressed by the ignorant, say: Peace.", source: "Quran 25:63" },
        { text: "Indeed, Allah commands justice and excellence.", source: "Quran 16:90" },
        { text: "Do not ridicule one another.", source: "Quran 49:11" },
        { text: "Make things easy; do not make them difficult.", source: "Bukhari & Muslim (meaning)" },
        { text: "The best of you are those who have the best manners.", source: "Hadith meaning" },
        { text: "Lower your voice.", source: "Quran 31:19" },
        { text: "Do not raise your voices above the Prophet’s voice.", source: "Quran 49:2 (adab principle)" },
        { text: "Gentleness beautifies everything.", source: "Sahih Muslim (meaning)" },
        { text: "Show mercy to those on earth; the One above will show mercy to you.", source: "Tirmidhi (meaning)" },
      ],

      "Dawah": [
        { text: "Invite to the way of your Lord with wisdom and good instruction.", source: "Quran 16:125" },
        { text: "Call to your Lord openly and privately.", source: "Quran 71 (theme)" },
        { text: "Who is better in speech than one who calls to Allah and does righteous deeds?", source: "Quran 41:33" },
        { text: "Speak kindly to him (Pharaoh).", source: "Quran 20:44 (theme)" },
        { text: "Let there arise a group inviting to all that is good.", source: "Quran 3:104" },
        { text: "Convey from me, even if one verse.", source: "Sahih al-Bukhari" },
        { text: "Do not argue except in the best manner.", source: "Quran 29:46 (theme)" },
        { text: "Repel evil with what is better.", source: "Quran 41:34" },
        { text: "Be a mercy to creation.", source: "Prophetic mission theme" },
        { text: "Make du‘a for guidance for others.", source: "General prophetic practice" },
      ],

      "Akhira": [
        { text: "Every soul shall taste death.", source: "Quran 3:185" },
        { text: "The Hereafter is better and more lasting.", source: "Quran 87:17" },
        { text: "Whoever does an atom’s weight of good will see it.", source: "Quran 99:7" },
        { text: "Race to forgiveness from your Lord.", source: "Quran 57:21" },
        { text: "The life of this world is but play and amusement.", source: "Quran 57:20 (theme)" },
        { text: "O my servants, fear Me.", source: "Quran theme" },
        { text: "Paradise is surrounded by hardships.", source: "Sahih Muslim (meaning)" },
        { text: "Hellfire is surrounded by desires.", source: "Sahih Muslim (meaning)" },
        { text: "Remember often the destroyer of pleasures (death).", source: "Tirmidhi (meaning)" },
        { text: "And to your Lord is the final return.", source: "Quran 53:42 (theme)" },
      ],

      "Family & Spouse": [
        { text: "And live with them in kindness.", source: "Quran 4:19" },
        { text: "He placed between you affection and mercy.", source: "Quran 30:21" },
        { text: "The best of you are the best to their families.", source: "Tirmidhi (meaning)" },
        { text: "Do not forget graciousness between you.", source: "Quran 2:237 (theme)" },
        { text: "And lower to them the wing of humility.", source: "Quran 17:24 (family principle)" },
        { text: "Maintain ties of kinship.", source: "Bukhari & Muslim (meaning)" },
        { text: "Whoever severs kinship will not enter Paradise.", source: "Bukhari & Muslim (meaning)" },
        { text: "Be gentle; gentleness beautifies matters.", source: "Sahih Muslim (meaning)" },
        { text: "And speak good words.", source: "Quran 2:83 (theme)" },
        { text: "Allah loves those who are just.", source: "Quran theme" },
      ],

      "Children": [
        { text: "O you who believe, protect yourselves and your families from a Fire.", source: "Quran 66:6" },
        { text: "My Lord, grant me from Yourself a good offspring.", source: "Quran 3:38 (theme)" },
        { text: "Teach them prayer.", source: "Hadith meaning (tarbiyah)" },
        { text: "Show mercy to the young.", source: "Hadith meaning" },
        { text: "Allah is gentle and loves gentleness.", source: "Sahih Muslim (meaning)" },
        { text: "And be patient.", source: "Quran theme" },
        { text: "Speak to people good words.", source: "Quran 2:83 (theme)" },
        { text: "Make du‘a for your children.", source: "Prophetic practice theme" },
        { text: "Truthfulness leads to righteousness.", source: "Bukhari & Muslim (meaning)" },
        { text: "Be an example before you demand change.", source: "Educational wisdom (principle)" },
      ],

      "Women in Islam": [
        { text: "Indeed, the most noble of you is the most righteous.", source: "Quran 49:13" },
        { text: "And live with them in kindness.", source: "Quran 4:19" },
        { text: "He placed between you affection and mercy.", source: "Quran 30:21" },
        { text: "The believers, men and women, are allies of one another.", source: "Quran 9:71" },
        { text: "Do not inherit women against their will.", source: "Quran 4:19 (theme)" },
        { text: "Whoever does righteous deeds—male or female—We will give them a good life.", source: "Quran 16:97" },
        { text: "Seeking knowledge is obligatory.", source: "Hadith meaning (applies to all)" },
        { text: "Do not harm and do not reciprocate harm.", source: "Hadith principle" },
        { text: "Honor is by taqwa, not gender.", source: "Quranic principle" },
        { text: "Allah is most just.", source: "Quranic principle" },
      ],

      "Sahaba & Parables": [
        { text: "Follow those who came before you with excellence.", source: "Quran 9:100 (theme)" },
        { text: "The example of good word is like a good tree.", source: "Quran 14:24" },
        { text: "The worldly life is like rain… then it becomes debris.", source: "Quran 57:20 (parable)" },
        { text: "Abu Bakr: truthfulness and humility are salvation.", source: "Attributed wisdom (principle)" },
        { text: "Umar: take account of yourselves before you are taken to account.", source: "Famous saying attributed to Umar (ra)" },
        { text: "Uthman: modesty is a shield.", source: "Sahabi virtue (theme)" },
        { text: "Ali: knowledge calls for action; if it responds it remains.", source: "Attributed wisdom" },
        { text: "Be companions of the righteous.", source: "Quran 9:119 (theme)" },
        { text: "Like the seller of musk and the blacksmith.", source: "Bukhari & Muslim (parable of companions)" },
        { text: "The believer is like a fresh tender plant, bent by winds, then stands.", source: "Hadith meaning" },
      ],
    }
  }
};
